def query_user_for_member(members):
    member = input("Enter the club member name: ")
    if member not in members:
        print("Name", member, "not found.")
    else:
        return member


def print_recommendations(member, similar_members, recommended_books):
    print(f"Recommendations for {member}:")
    for book in recommended_books:
        print(f"\t{book[1]} by {book[0]}")
    print(f"List generated by recommendations of {similar_members[0]} and {similar_members[1]}")
