def ask_for_member(members):
    member = input("Enter the club member name: ")
    if member not in members:
        print("Name", member, "not found.")
    else:
        return member


def print_recommendations(member, similar_members, recommended_books):
    sorted_books = sorted(recommended_books, key=lambda x: x[1].removeprefix("The"))
    print(f"Recommendations for {member}:")
    for i in sorted_books:
        print(f"\t{i[1]} by {i[0]}")
    print(f"List generated by recommendations of {similar_members[0]} and {similar_members[1]}")
